default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: super-test-app_development

test:
  <<: *default
  database: super-test-app_test

production:
  <<: *default
  database: super-test-app_production
